//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LatihanEF.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mahasiswa
    {
        public string Nim { get; set; }
        public string Nama { get; set; }
        public string Jurusan { get; set; }
    }
}
